### ISSUE TITLE
Command line iOS screen recording (using physical devices)

### ISSUE THREAD

**Issue by IntergalacticPenguin** [IntergalacticPenguin/mobile-toolkit#177]
### 🐞 Whats wrong
`irecord` isnt recording iOS device screen using command line interface
### 🌈 Desired state
Record iOS physical device screen without Quick Time hassle
### 📏 Challenges
I am not aware of any other way of iOS screen recording using command line
### 📂 Sources
I was able to get some information from www.rotato.xyz they send me some clues on how to start.
```
The way Rotato does it in Swift/Cocoa is by enabling screen capture devices, and then simply treating it
as a camera via AVCaptureDevice. I haven't seen any stand-alone command-line apps that does this,
but it's definitely not impossible, so you might be able to find something on GitHub, or even build it
yourself.

This search might yield something interesting
https://github.com/search?q=kCMIOHardwarePropertyAllowScreenCaptureDevices&type=Code
```

https://github.com/matthutchinson/videosnap

**Comment by mkj-is** [comment]
From the version 0.0.5 `videosnap` now supports recording from devices. The hard thing is to handle distribution, since you need to build it yourself in Xcode due to code-signing and sandboxing on macOS.

**Comment by IntergalacticPenguin** [comment]
Seems like there is no need to handle anything special regarding distribution.
All I had to do was install the tool using standard .pkg file.

https://github.com/IntergalacticPenguin/mobile-toolkit/pull/204
