### ISSUE TITLE
icheckdevice time check isnt precise enough

### ISSUE THREAD

**Issue by IntergalacticPenguin** [IntergalacticPenguin/mobile-toolkit#178]
### 🐞 Whats wrong
Sometimes there is a false positive result while checking if automatic time & date is enabled
### 🌈 Desired state
0% false positives
### 📏 Challenges
There is nothing like `adb shell getprop <xy>` on iOS
### 📂 Sources
404 NOT FOUND

**Comment by radimvaculik** [comment]
There is no better option. If you check `ideviceinfo`, you can only get these properties:

```
TimeIntervalSince1970: 1609282800.307679
TimeZone: Europe/Prague
TimeZoneOffsetFromUTC: 3600.000000
Uses24HourClock: false
```
(btw. property `Uses24HourClock` is also wrong).

---

You can compare date & time with seconds and apply couple seconds delta range - for example 5 seconds delta.
