### ISSUE TITLE
Switch to "go-ios" from "libimobiledevice"

### ISSUE THREAD

**Issue by IntergalacticPenguin** [IntergalacticPenguin/mobile-toolkit#219]
### 🐞 Whats wrong
libimobiledevice tool is not being supported actively by its authors.
### 🌈 Desired state
Unlock more possibilities to implement new features and optimize scripts.
New features could include launching and killing installed apps and much more! 🙀
### 📏 Challenges
Rework all iOS scripts from scratch with different open source utility.
### 📂 Sources
https://github.com/danielpaulus/go-ios

**Comment by danielpaulus** [comment]
If you want crashlogs, just open an issue. Should be easy to add.
