### ISSUE TITLE
/mobile-toolkit/aloremipsum: line 12: adb_paste: command not found

### ISSUE THREAD

**Issue by hasansidd** [IntergalacticPenguin/mobile-toolkit#62]
I believe I have platform-tools and mobile-toolkit in PATH. I've tried other commands such as apaste and abounds and they work

**Comment by IntergalacticPenguin** [comment]
Oh yea thats my bad, gonna fix it right away

**Comment by IntergalacticPenguin** [comment]
Okay, navigate to the cloned folder and use ```git pull``` then it should work, thanks for your cooperation :)

**Comment by hasansidd** [comment]
Thanks working well
