### ISSUE TITLE
Cannot use ! without escaping it or using single quotes for apaste

### ISSUE THREAD

**Issue by hasansidd** [IntergalacticPenguin/mobile-toolkit#63]
I don't know if this is just a limitation of bash but would it be possible to escape the exclamation in code or will it just be something to keep in mind to either use single quotes or escape?

**Comment by IntergalacticPenguin** [comment]
I think it its a bash limitation. https://superuser.com/questions/163515/bash-how-to-pass-command-line-arguments-containing-special-characters
